version: '3.8'

services:
  webapi:
    build:
      context: ./min-api-with-mongo/WebApi
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
