version: '3.9'
services:
  webapi:
    build: WebApi
    restart: always
    depends_on:
      - mongodb
    environment:
      DatabaseSettings__ConnectionString: "mongodb://gbs:geheim@mongodb:27017"
      DatabaseSettings__TestX: "X von Docker compose"
      DatabaseSettings__TestY: "Y von Docker compose"
    ports: 
      - 5001:5001
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INTDB_ROOT_USERNAME: gbs
      MONGO_INTDB_ROOT_PASSWORD: geheim
    volumes:
      - mongoData:/data/db
volumes:
  mongoData: 